#!/usr/bin/env bash
# Configures HAproxy on a new Ubuntu machine

sudo apt-get -y update
sudo apt-install -y haproxy

echo -e "\nfrontend iamzidane.tech\n\
\tbind *:80\n\
\tmode http\n\
\tdefault_backend web-backend\n" >> /etc/haproxy/haproxy.cfg

echo -e "\nbackend web-backend\n\
\tbalance roundrobin\n\
\tserver 434106-web-01 54.196.38.185:80 check\n\
\tserver 434106-web-02 52.201.177.148:80 check" >> /etc/haproxy/haproxy.cfg

echo "ENABLED=1" >> /etc/default/haproxy

sudo service haproxy restart
