#!/usr/bin/env bash
# Configures HAproxy on a new Ubuntu machine

#  update the package
sudo apt-get -y update
# install HAProxy
sudo apt-get -y install haproxy

# HAProxy configuration
config="
frontend iamzidane.tech
  bind *:80
  mode http
  default_backend web_servers

backend web_servers
  balance roundrobin
  server 434106-web-01 54.196.38.185:80 check
  server 434106-web-02 35.153.232.27:80 check
"

# append the configurations to haproxy.cfg
echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
# activate the HAProxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy > /dev/null

# restart the HAProxy
sudo service haproxy restart
