#!/usr/bin/env bash
# A script that manages "manage_my_process"

case "$1" in
	"start")
		echo "manage_my_process started"
		./manage_my_process &
		echo "$!" > /var/run/my_process.pid
		;;
	"stop")
		pkill -f "manage_my_process"
		rm "/var/run/my_process.pid"
		echo "manage_my_process stopped"
		;;
	"restart")
		pkill -f "manage_my_process"
		rm "/var/run/my_process.pid"
		./manage_my_process &
		echo "$!" > /var/run/my_process.pid
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
esac
